# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.__version__

'1.26.4'

2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np
zero_vector = np.full([1,10],0)
zero_vector

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
import numpy as np
vector = np.full([1,7],7,dtype=int)
vector

array([[7, 7, 7, 7, 7, 7, 7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
import numpy as np
even_nums = np.arange(10,101,2)
even_nums

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
import numpy as np
random_arr = np.random.rand(5)
reverse_arr = np.flip(random_arr)
reverse_arr,random_arr

(array([0.5291886 , 0.75450813, 0.43110216, 0.30299293, 0.94436541]),
 array([0.94436541, 0.30299293, 0.43110216, 0.75450813, 0.5291886 ]))

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [47]:
import numpy as np
matrix = np.arange(0,9,1)
res = matrix.reshape((3,3))
res

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
import numpy as np
matrix = np.eye(4,k=1)
matrix

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
import numpy as np
matrix = np.full([4,4],7)
np.fill_diagonal(matrix,[1,2,3,4])
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
import numpy as np
matrix = np.tile(np.arange(5),(5,1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np
matrix = np.random.rand(10,10)
avg_rows = matrix.mean(axis=1,keepdims=True)
res = matrix - avg_rows
res

array([[-0.32811626, -0.11532257, -0.12393651, -0.23659911,  0.33160607,
        -0.00433166, -0.29316605,  0.05951808,  0.44515647,  0.26519155],
       [-0.16849116, -0.32081265, -0.32249146,  0.08347338,  0.08568286,
         0.30665108,  0.3269523 ,  0.01980136,  0.371403  , -0.38216872],
       [ 0.10100129, -0.15302617, -0.36517885,  0.0484837 ,  0.02791414,
        -0.05609389,  0.260994  ,  0.00066145,  0.09911415,  0.03613018],
       [ 0.04961183,  0.06478774, -0.3747214 ,  0.3633066 ,  0.32365763,
         0.30154849,  0.09704513, -0.54295007, -0.30878652,  0.02650057],
       [-0.0138138 , -0.01179476, -0.48921398,  0.37510184,  0.06127719,
         0.15664425,  0.26528852, -0.15351677, -0.00853198, -0.18144052],
       [ 0.44986846, -0.23432259,  0.05642556, -0.12366562, -0.2137498 ,
         0.08799896,  0.12845404, -0.00999471,  0.04063836, -0.18165266],
       [ 0.36746323, -0.01822753, -0.49312501, -0.35722402, -0.35002489,
         0.26232601,  0.33110649,  0.26665149

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
import numpy as np
matrix = np.random.rand(10,10)
column_medians = np.median(matrix,axis=0)
res = matrix - column_medians
res

array([[-0.35436856, -0.2596185 ,  0.07411972, -0.06412333, -0.13048421,
        -0.41427799, -0.70885422, -0.31432115, -0.26871233,  0.14082507],
       [ 0.12394406,  0.66526962,  0.31942332,  0.28269012,  0.21618372,
        -0.1616853 ,  0.05222748,  0.18784532,  0.19221668,  0.13429025],
       [ 0.24923406,  0.13335667, -0.51188291,  0.32081215, -0.20168188,
         0.16257817, -0.31458965, -0.53588443,  0.37167283,  0.15060805],
       [-0.49486119, -0.2219213 , -0.26731712,  0.02238463, -0.30100987,
        -0.00875311,  0.16376073, -0.51240964, -0.01727726,  0.33224789],
       [-0.29014874,  0.48634897, -0.46623397,  0.29835113, -0.41865643,
         0.00875311, -0.01223673,  0.18063236,  0.16835874,  0.0862081 ],
       [-0.02421467,  0.04324905, -0.07349126,  0.36812488,  0.13223831,
        -0.56749211,  0.10375304,  0.24017744, -0.19250926, -0.30156552],
       [ 0.24297624, -0.0678042 , -0.40645246, -0.04909601,  0.41036051,
         0.07726894, -0.248561  ,  0.24748552

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
import numpy as np
matrix = np.random.rand(5,5)
column_max = matrix.max(axis=1,keepdims=True)
column_min = matrix.min(axis=1,keepdims=True)
res = np.hstack((matrix,column_max,column_min))
res

array([[0.69995553, 0.03448321, 0.53523763, 0.08719222, 0.53968229,
        0.69995553, 0.03448321],
       [0.97568339, 0.23825539, 0.79295365, 0.66082115, 0.77463599,
        0.97568339, 0.23825539],
       [0.049707  , 0.01820456, 0.99743923, 0.75674189, 0.91600908,
        0.99743923, 0.01820456],
       [0.98509444, 0.23157296, 0.82026925, 0.93414451, 0.33223511,
        0.98509444, 0.23157296],
       [0.16705201, 0.33818844, 0.95368267, 0.39569118, 0.24749958,
        0.95368267, 0.16705201]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [ ]:
import numpy as np
vector = np.arange(1,52)
even_nums = vector[vector % 2 == 0]
odd_nums = vector[vector % 2 != 0]
even_matrix = even_nums.reshape(-1,1)
odd_matrix = odd_nums.reshape(1,-1)
product_matrix = np.dot(even_matrix,odd_matrix)
square_matrix = product_matrix[:25,:25]
reverse_matrix = np.flip(square_matrix)
reverse_matrix

array([[2450, 2350, 2250, 2150, 2050, 1950, 1850, 1750, 1650, 1550, 1450,
        1350, 1250, 1150, 1050,  950,  850,  750,  650,  550,  450,  350,
         250,  150,   50],
       [2352, 2256, 2160, 2064, 1968, 1872, 1776, 1680, 1584, 1488, 1392,
        1296, 1200, 1104, 1008,  912,  816,  720,  624,  528,  432,  336,
         240,  144,   48],
       [2254, 2162, 2070, 1978, 1886, 1794, 1702, 1610, 1518, 1426, 1334,
        1242, 1150, 1058,  966,  874,  782,  690,  598,  506,  414,  322,
         230,  138,   46],
       [2156, 2068, 1980, 1892, 1804, 1716, 1628, 1540, 1452, 1364, 1276,
        1188, 1100, 1012,  924,  836,  748,  660,  572,  484,  396,  308,
         220,  132,   44],
       [2058, 1974, 1890, 1806, 1722, 1638, 1554, 1470, 1386, 1302, 1218,
        1134, 1050,  966,  882,  798,  714,  630,  546,  462,  378,  294,
         210,  126,   42],
       [1960, 1880, 1800, 1720, 1640, 1560, 1480, 1400, 1320, 1240, 1160,
        1080, 1000,  920,  840,  760,  680,  600,  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
import numpy as np
chessboard = np.full([8,8],0)
chessboard[1::2,::2] = 1
chessboard[::2,1::2] = 1
chessboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])